/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;
import  frame.SC_login;
import java.util.Calendar;
public class Menu extends javax.swing.JFrame {
connection con;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        con=new connection();
        con.abreConexion();
        this.setLocationRelativeTo(null);
        String consultaUser=con.consultaUser(SC_login.nombre);
        lblNombre.setText("Usuario " + consultaUser);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        MIAgregarEmpaque = new javax.swing.JMenuItem();
        miEliminarEmpaque = new javax.swing.JMenuItem();
        MIActualizar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        miEliminarLabo = new javax.swing.JMenuItem();
        miActualizarLabo = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(0, 255, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 300));

        lblNombre.setBackground(new java.awt.Color(102, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 540, 30));

        jMenuBar1.setOpaque(false);

        jMenu1.setBackground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("Recursos humanos");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Compras");

        jMenu4.setText("Empaques");

        MIAgregarEmpaque.setText("Nuevo Empaque");
        MIAgregarEmpaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIAgregarEmpaqueActionPerformed(evt);
            }
        });
        jMenu4.add(MIAgregarEmpaque);

        miEliminarEmpaque.setText("Eliminar Empaque");
        miEliminarEmpaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEliminarEmpaqueActionPerformed(evt);
            }
        });
        jMenu4.add(miEliminarEmpaque);

        MIActualizar.setText("Actualizar Empaque");
        MIActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIActualizarActionPerformed(evt);
            }
        });
        jMenu4.add(MIActualizar);

        jMenu2.add(jMenu4);

        jMenu5.setText("Laboratorios");

        jMenuItem11.setText("Nuevo Laboratorio");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        miEliminarLabo.setText("Eliminar Laboratorio");
        miEliminarLabo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEliminarLaboActionPerformed(evt);
            }
        });
        jMenu5.add(miEliminarLabo);

        miActualizarLabo.setText("Actualizar Laboratoio");
        miActualizarLabo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miActualizarLaboActionPerformed(evt);
            }
        });
        jMenu5.add(miActualizarLabo);

        jMenu2.add(jMenu5);

        jMenu6.setText("Unidad Medida");

        jMenuItem6.setText("Agregar Medida");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuItem10.setText("Eliminar Medida");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenuItem12.setText("Actualizar Medida");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem12);

        jMenu2.add(jMenu6);

        jMenu7.setText("Categorias");

        jMenuItem1.setText("Añadir Categorias");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem1);

        jMenuItem2.setText("Eliminar Categorias");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        jMenuItem3.setText("Update Categorias");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem3);

        jMenuItem4.setText("Consultar categorias");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem4);

        jMenu2.add(jMenu7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ventas");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        InsertarLab IL=new InsertarLab();
        IL.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    
    
    private void MIAgregarEmpaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIAgregarEmpaqueActionPerformed
        Empaques AM=new Empaques();
        AM.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_MIAgregarEmpaqueActionPerformed

    private void miEliminarEmpaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEliminarEmpaqueActionPerformed
        eliminar el=new eliminar();
        el.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_miEliminarEmpaqueActionPerformed

    private void MIActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIActualizarActionPerformed
        ActualizarEmpaques AE=new ActualizarEmpaques();
        AE.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_MIActualizarActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        UnidadMedia UM=new UnidadMedia();
        UM.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        UnidadMediaBorrar UMB=new  UnidadMediaBorrar();
        UMB.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        UnidadMediaUpdate UMU=new  UnidadMediaUpdate();
        UMU.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        categoriaInsertar cI=new categoriaInsertar();
        cI.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        categoriaEliminar cE=new categoriaEliminar();
        cE.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        categoriaModificar cM=new categoriaModificar();
        cM.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void miActualizarLaboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miActualizarLaboActionPerformed
       ActualizarLab AL=new  ActualizarLab();
       AL.setVisible(true);
       dispose();
    }//GEN-LAST:event_miActualizarLaboActionPerformed

    private void miEliminarLaboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEliminarLaboActionPerformed
        EliminarLab Ela=new EliminarLab();
        Ela.setVisible(true);
        dispose();
    }//GEN-LAST:event_miEliminarLaboActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        categoriaConsultaTodos c=new categoriaConsultaTodos();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MIActualizar;
    private javax.swing.JMenuItem MIAgregarEmpaque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JMenuItem miActualizarLabo;
    private javax.swing.JMenuItem miEliminarEmpaque;
    private javax.swing.JMenuItem miEliminarLabo;
    // End of variables declaration//GEN-END:variables
}
