/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

/**
 *
 * @author rcerv
 */
public class pedidos_Agregar extends javax.swing.JFrame {

    /**
     * Creates new form pedidos_seguimiento
     */
     connection con;
    Object qht;
    public pedidos_Agregar() {
          initComponents();
       con=new connection();
       con.abreConexion();
       this.setLocationRelativeTo(null);
       con.consultaPedidos(table_pedidos_Agregar);
       
       txf_pedidosAgregar_idPedido.setText(String.valueOf(con.consultaIDPedidos()+1));
       txf_pedidosAgregar_fechaDeRegistro.setText("YYYY/MM/DD");
       txf_pedidosAgregar_fechaDeRecepcion.setText("YYYY/MM/DD");
    }

    Object datos[];
    String x;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txf_pedidosAgregar_fechaDeRecepcion = new javax.swing.JTextField();
        txf_pedidosAgregar_idSucursal = new javax.swing.JTextField();
        txf_pedidosAgregar_totalAPagar = new javax.swing.JTextField();
        txf_pedidosAgregar_cantidadPagada = new javax.swing.JTextField();
        txf_pedidosAgregar_idProveedor = new javax.swing.JTextField();
        txf_pedidosAgregar_idEmpleado = new javax.swing.JTextField();
        txf_pedidosAgregar_fechaDeRegistro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_pedidos_Agregar = new javax.swing.JTable();
        button_pedidosAgregar_Agregar = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        txf_pedidosAgregar_idPedido = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Fecha de registro");

        jLabel3.setText("Fecha de recepcion");

        jLabel4.setText("Total a pagar");

        jLabel5.setText("Cantidad pagada");

        jLabel7.setText("ID Proveedor");

        jLabel8.setText("ID Sucursal");

        jLabel9.setText("ID Empleado");

        table_pedidos_Agregar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_pedidos_Agregar);

        button_pedidosAgregar_Agregar.setText("Agregar");
        button_pedidosAgregar_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_pedidosAgregar_AgregarMouseClicked(evt);
            }
        });

        jLabel6.setText("ID Pedido");

        jMenu1.setText("Opciones");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txf_pedidosAgregar_idEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_pedidosAgregar_idSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_pedidosAgregar_idProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(txf_pedidosAgregar_cantidadPagada, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(txf_pedidosAgregar_totalAPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(txf_pedidosAgregar_fechaDeRecepcion, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(txf_pedidosAgregar_fechaDeRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(txf_pedidosAgregar_idPedido)))
                    .addComponent(button_pedidosAgregar_Agregar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txf_pedidosAgregar_idPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txf_pedidosAgregar_fechaDeRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txf_pedidosAgregar_fechaDeRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txf_pedidosAgregar_totalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txf_pedidosAgregar_cantidadPagada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_pedidosAgregar_idProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txf_pedidosAgregar_idSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txf_pedidosAgregar_idEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button_pedidosAgregar_Agregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Menu Me=new Menu();
        Me.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void button_pedidosAgregar_AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_pedidosAgregar_AgregarMouseClicked
        // TODO add your handling code here: 
       
        datos = new Object[9];
        datos[0] = Integer.parseInt(txf_pedidosAgregar_idPedido.getText());
        datos[1] = String.valueOf(txf_pedidosAgregar_fechaDeRegistro.getText());
        datos[2] = String.valueOf(txf_pedidosAgregar_fechaDeRecepcion.getText());
        datos[3] = Float.valueOf(txf_pedidosAgregar_totalAPagar.getText());
        datos[4] = Float.valueOf(txf_pedidosAgregar_cantidadPagada.getText());
        datos[5] = "D";
        datos[6] = Integer.parseInt(txf_pedidosAgregar_idProveedor.getText());
        datos[7] = Integer.parseInt(txf_pedidosAgregar_idSucursal.getText());
        datos[8] = Integer.parseInt(txf_pedidosAgregar_idEmpleado.getText());
        con.insertarPedido(datos,table_pedidos_Agregar);
   
        //--------------------Borrado de espacios
       txf_pedidosAgregar_idPedido.setText("");
       txf_pedidosAgregar_fechaDeRegistro.setText("YYYY/MM/DD");
       txf_pedidosAgregar_fechaDeRecepcion.setText("YYYY/MM/DD");
       txf_pedidosAgregar_totalAPagar.setText("");
       txf_pedidosAgregar_cantidadPagada.setText("");
       txf_pedidosAgregar_idProveedor.setText("");
       txf_pedidosAgregar_idSucursal.setText("");
       txf_pedidosAgregar_idEmpleado.setText("");
        
        txf_pedidosAgregar_idPedido.setText(String.valueOf(con.consultaIDPedidos()+1));
    }//GEN-LAST:event_button_pedidosAgregar_AgregarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pedidos_Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pedidos_Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pedidos_Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pedidos_Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pedidos_Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton button_pedidosAgregar_Agregar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_pedidos_Agregar;
    private javax.swing.JTextField txf_pedidosAgregar_cantidadPagada;
    private javax.swing.JTextField txf_pedidosAgregar_fechaDeRecepcion;
    private javax.swing.JTextField txf_pedidosAgregar_fechaDeRegistro;
    private javax.swing.JTextField txf_pedidosAgregar_idEmpleado;
    private javax.swing.JTextField txf_pedidosAgregar_idPedido;
    private javax.swing.JTextField txf_pedidosAgregar_idProveedor;
    private javax.swing.JTextField txf_pedidosAgregar_idSucursal;
    private javax.swing.JTextField txf_pedidosAgregar_totalAPagar;
    // End of variables declaration//GEN-END:variables
}
