package frame;

import javax.swing.JOptionPane;

public class SC_login extends javax.swing.JFrame {

    connection con;
    public static String nombre;
   
    public SC_login() {
        initComponents();
        con = new connection();
        con.abreConexion();
        this.setLocationRelativeTo(null);
        System.out.println("hola prros");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        lblUN = new javax.swing.JLabel();
        txtUN = new javax.swing.JTextField();
        lblPW = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        btnIni = new javax.swing.JButton();
        txtPW = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUN.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        lblUN.setForeground(new java.awt.Color(0, 0, 0));
        lblUN.setText("Username:");
        getContentPane().add(lblUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 27));
        getContentPane().add(txtUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 150, 30));

        lblPW.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        lblPW.setForeground(new java.awt.Color(0, 0, 0));
        lblPW.setText("Password:");
        getContentPane().add(lblPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 25));

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        btnIni.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnIni.setText("LOGIN");
        btnIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniActionPerformed(evt);
            }
        });
        getContentPane().add(btnIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 120, 40));
        getContentPane().add(txtPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 150, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/descarga (1)_1.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 120, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/DESCARGA.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniActionPerformed
        if ("".equals(txtUN.getText())) {
            JOptionPane.showMessageDialog(null, "Falta usuario");
        } else if ("".equals(txtPW.getText())) {
            JOptionPane.showMessageDialog(null, "Falta Contraseña");
        }
        int res = con.login(txtUN.getText(), txtPW.getText());
        nombre=txtUN.getText();
        Menu m = new Menu();
        if (res == 1) {
            m.setVisible(true);
            dispose();
        } else if (res == 2) {
            m.setVisible(true);
            dispose();
            nombre=txtUN.getText();
        }


    }//GEN-LAST:event_btnIniActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SC_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SC_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SC_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SC_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SC_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIni;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblPW;
    private javax.swing.JLabel lblUN;
    private javax.swing.JPasswordField txtPW;
    private javax.swing.JTextField txtUN;
    // End of variables declaration//GEN-END:variables
}
